## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

# Import pandas and read the charity_data.csv from the provided cloud URL.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN", "NAME"])

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_df["APPLICATION_TYPE"].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
application_type_counts = application_df["APPLICATION_TYPE"].value_counts()
application_types_to_replace = application_type_counts[application_type_counts < 500].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts
classification_counts = application_df["CLASSIFICATION"].value_counts()

# Choose a cutoff value and create a list of classification types to be replaced
classification_types_to_replace = classification_counts[classification_counts < 500].index.tolist()

# Replace in dataframe
for cls in classification_types_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts greater than 1
classification_counts = application_df["CLASSIFICATION"].value_counts()

# Filter for counts greater than 1
classification_counts_above_1 = classification_counts[classification_counts > 1]

# Display the results
print(classification_counts_above_1)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: count, dtype: int64

In [8]:
# Choose a cutoff value, for example, classifications with fewer than 100 occurrences
cutoff_value = 100

# Create a list of classifications to be replaced
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric using pd.get_dummies
application_df = pd.get_dummies(application_df, drop_first=True)

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop(columns=["IS_SUCCESSFUL"])  # Features
y = application_df["IS_SUCCESSFUL"]  # Target variable

# Split the preprocessed data into a training and testing dataset
from sklearn.model_selection import train_test_split

# Split the data into training and testing datasets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
from keras.models import Sequential
from keras.layers import Dense

# Define the model - deep neural net
nn = tf.keras.models.Sequential()

# First hidden layer
# Assuming the input features are X_train_scaled with shape (n_samples, n_features)
nn.add(tf.keras.layers.Dense(units=128, activation='relu', input_dim=X_train_scaled.shape[1]))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=64, activation='relu'))

# Output layer
# For binary classification, we use 1 unit with a sigmoid activation function
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         4,864 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,185 (51.50 KB)

 Trainable params: 13,185 (51.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
# Compile the model
nn.compile(loss='binary_crossentropy',   # Loss function for binary classification
           optimizer='adam',             # Optimizer (Adam is commonly used)
           metrics=['accuracy'])         # Metrics to evaluate model performance

In [15]:
# Train the model
history = nn.fit(X_train_scaled, y_train,
                 epochs=100,         # Number of epochs
                 batch_size=32,      # Batch size
                 validation_data=(X_test_scaled, y_test),  # Validation data
                 verbose=2)          # Verbose output (level 2 shows a progress bar)

Epoch 1/100
858/858 - 4s - 5ms/step - accuracy: 0.7223 - loss: 0.5670 - val_accuracy: 0.7268 - val_loss: 0.5603
Epoch 2/100
858/858 - 3s - 3ms/step - accuracy: 0.7299 - loss: 0.5553 - val_accuracy: 0.7259 - val_loss: 0.5613
Epoch 3/100
858/858 - 3s - 4ms/step - accuracy: 0.7293 - loss: 0.5513 - val_accuracy: 0.7289 - val_loss: 0.5616
Epoch 4/100
858/858 - 4s - 5ms/step - accuracy: 0.7312 - loss: 0.5501 - val_accuracy: 0.7265 - val_loss: 0.5583
Epoch 5/100
858/858 - 3s - 3ms/step - accuracy: 0.7317 - loss: 0.5483 - val_accuracy: 0.7229 - val_loss: 0.5580
Epoch 6/100
858/858 - 3s - 3ms/step - accuracy: 0.7305 - loss: 0.5472 - val_accuracy: 0.7267 - val_loss: 0.5586
Epoch 7/100
858/858 - 5s - 5ms/step - accuracy: 0.7317 - loss: 0.5467 - val_accuracy: 0.7259 - val_loss: 0.5586
Epoch 8/100
858/858 - 2s - 3ms/step - accuracy: 0.7321 - loss: 0.5468 - val_accuracy: 0.7249 - val_loss: 0.5561
Epoch 9/100
858/858 - 3s - 3ms/step - accuracy: 0.7322 - loss: 0.5458 - val_accuracy: 0.7233 - val_loss: 0.5566
Epoch 10/100
858/858 - 7s - 8ms/step - accuracy: 0.7336 - loss: 0.5448 - val_accuracy: 0.7277 - val_loss: 0.5558
Epoch 11/100
858/858 - 5s - 6ms/step - accuracy: 0.7346 - loss: 0.5445 - val_accuracy: 0.7281 - val_loss: 0.5562
Epoch 12/100
858/858 - 7s - 8ms/step - accuracy: 0.7351 - loss: 0.5442 - val_accuracy: 0.7241 - val_loss: 0.5547
Epoch 13/100
858/858 - 5s - 5ms/step - accuracy: 0.7351 - loss: 0.5434 - val_accuracy: 0.7280 - val_loss: 0.5547
Epoch 14/100
858/858 - 3s - 3ms/step - accuracy: 0.7347 - loss: 0.5435 - val_accuracy: 0.7258 - val_loss: 0.5550
Epoch 15/100
858/858 - 3s - 3ms/step - accuracy: 0.7360 - loss: 0.5429 - val_accuracy: 0.7280 - val_loss: 0.5537
Epoch 16/100
858/858 - 5s - 5ms/step - accuracy: 0.7357 - loss: 0.5422 - val_accuracy: 0.7254 - val_loss: 0.5562
Epoch 17/100
858/858 - 3s - 3ms/step - accuracy: 0.7351 - loss: 0.5429 - val_accuracy: 0.7252 - val_loss: 0.5563
Epoch 18/100
858/858 - 3s - 3ms/step - accuracy: 0.7360 - loss: 0.5420 - val_accuracy: 0.7267 - val_loss: 0.5565
Epoch 19/100
858/858 - 3s - 4ms/step - accuracy: 0.7352 - loss: 0.5415 - val_accuracy: 0.7289 - val_loss: 0.5561
Epoch 20/100
858/858 - 3s - 3ms/step - accuracy: 0.7380 - loss: 0.5411 - val_accuracy: 0.7235 - val_loss: 0.5553
Epoch 21/100
858/858 - 5s - 6ms/step - accuracy: 0.7367 - loss: 0.5414 - val_accuracy: 0.7300 - val_loss: 0.5531
Epoch 22/100
858/858 - 2s - 3ms/step - accuracy: 0.7367 - loss: 0.5406 - val_accuracy: 0.7261 - val_loss: 0.5551
Epoch 23/100
858/858 - 4s - 4ms/step - accuracy: 0.7353 - loss: 0.5406 - val_accuracy: 0.7300 - val_loss: 0.5541
Epoch 24/100
858/858 - 2s - 3ms/step - accuracy: 0.7372 - loss: 0.5401 - val_accuracy: 0.7299 - val_loss: 0.5566
Epoch 25/100
858/858 - 3s - 3ms/step - accuracy: 0.7372 - loss: 0.5402 - val_accuracy: 0.7287 - val_loss: 0.5539
Epoch 26/100
858/858 - 2s - 3ms/step - accuracy: 0.7376 - loss: 0.5397 - val_accuracy: 0.7281 - val_loss: 0.5538
Epoch 27/100
858/858 - 3s - 3ms/step - accuracy: 0.7365 - loss: 0.5401 - val_accuracy: 0.7293 - val_loss: 0.5551
Epoch 28/100
858/858 - 3s - 4ms/step - accuracy: 0.7369 - loss: 0.5393 - val_accuracy: 0.7287 - val_loss: 0.5548
Epoch 29/100
858/858 - 2s - 2ms/step - accuracy: 0.7372 - loss: 0.5391 - val_accuracy: 0.7303 - val_loss: 0.5553
Epoch 30/100
858/858 - 2s - 3ms/step - accuracy: 0.7375 - loss: 0.5390 - val_accuracy: 0.7257 - val_loss: 0.5565
Epoch 31/100
858/858 - 3s - 4ms/step - accuracy: 0.7377 - loss: 0.5390 - val_accuracy: 0.7265 - val_loss: 0.5584
Epoch 32/100
858/858 - 4s - 5ms/step - accuracy: 0.7380 - loss: 0.5382 - val_accuracy: 0.7277 - val_loss: 0.5567
Epoch 33/100
858/858 - 4s - 4ms/step - accuracy: 0.7379 - loss: 0.5388 - val_accuracy: 0.7267 - val_loss: 0.5575
Epoch 34/100
858/858 - 5s - 6ms/step - accuracy: 0.7375 - loss: 0.5384 - val_accuracy: 0.7264 - val_loss: 0.5561
Epoch 35/100
858/858 - 5s - 6ms/step - accuracy: 0.7375 - loss: 0.5384 - val_accuracy: 0.7300 - val_loss: 0.5552
Epoch 36/100
858/858 - 3s - 3ms/step - accuracy: 0.7386 - loss: 0.5380 - val_accuracy: 0.7277 - val_loss: 0.5557
Epoch 37/100
858/858 - 5s - 6ms/step - accuracy: 0.7386 - loss: 0.5377 - val_accuracy: 0.7290 - val_loss: 0.5545
Epoch 38/100
858/858 - 4s - 4ms/step - accuracy: 0.7374 - loss: 0.5375 - val_accuracy: 0.7284 - val_loss: 0.5584
Epoch 39/100
858/858 - 4s - 5ms/step - accuracy: 0.7381 - loss: 0.5376 - val_accuracy: 0.7277 - val_loss: 0.5554
Epoch 40/100
858/858 - 2s - 3ms/step - accuracy: 0.7387 - loss: 0.5372 - val_accuracy: 0.7294 - val_loss: 0.5564
Epoch 41/100
858/858 - 3s - 3ms/step - accuracy: 0.7386 - loss: 0.5376 - val_accuracy: 0.7278 - val_loss: 0.5554
Epoch 42/100
858/858 - 3s - 4ms/step - accuracy: 0.7379 - loss: 0.5371 - val_accuracy: 0.7280 - val_loss: 0.5566
Epoch 43/100
858/858 - 4s - 5ms/step - accuracy: 0.7385 - loss: 0.5369 - val_accuracy: 0.7276 - val_loss: 0.5595
Epoch 44/100
858/858 - 3s - 3ms/step - accuracy: 0.7380 - loss: 0.5376 - val_accuracy: 0.7287 - val_loss: 0.5560
Epoch 45/100
858/858 - 5s - 6ms/step - accuracy: 0.7386 - loss: 0.5364 - val_accuracy: 0.7286 - val_loss: 0.5570
Epoch 46/100
858/858 - 5s - 5ms/step - accuracy: 0.7391 - loss: 0.5365 - val_accuracy: 0.7299 - val_loss: 0.5571
Epoch 47/100
858/858 - 3s - 3ms/step - accuracy: 0.7386 - loss: 0.5365 - val_accuracy: 0.7284 - val_loss: 0.5580
Epoch 48/100
858/858 - 3s - 3ms/step - accuracy: 0.7385 - loss: 0.5364 - val_accuracy: 0.7280 - val_loss: 0.5594
Epoch 49/100
858/858 - 5s - 6ms/step - accuracy: 0.7386 - loss: 0.5360 - val_accuracy: 0.7294 - val_loss: 0.5588
Epoch 50/100
858/858 - 3s - 3ms/step - accuracy: 0.7390 - loss: 0.5360 - val_accuracy: 0.7255 - val_loss: 0.5595
Epoch 51/100
858/858 - 3s - 3ms/step - accuracy: 0.7387 - loss: 0.5365 - val_accuracy: 0.7229 - val_loss: 0.5592
Epoch 52/100
858/858 - 3s - 4ms/step - accuracy: 0.7399 - loss: 0.5362 - val_accuracy: 0.7268 - val_loss: 0.5582
Epoch 53/100
858/858 - 3s - 3ms/step - accuracy: 0.7395 - loss: 0.5359 - val_accuracy: 0.7274 - val_loss: 0.5580
Epoch 54/100
858/858 - 2s - 3ms/step - accuracy: 0.7381 - loss: 0.5357 - val_accuracy: 0.7281 - val_loss: 0.5582
Epoch 55/100
858/858 - 3s - 3ms/step - accuracy: 0.7392 - loss: 0.5359 - val_accuracy: 0.7297 - val_loss: 0.5590
Epoch 56/100
858/858 - 3s - 3ms/step - accuracy: 0.7389 - loss: 0.5356 - val_accuracy: 0.7277 - val_loss: 0.5578
Epoch 57/100
858/858 - 4s - 4ms/step - accuracy: 0.7388 - loss: 0.5354 - val_accuracy: 0.7284 - val_loss: 0.5635
Epoch 58/100
858/858 - 3s - 3ms/step - accuracy: 0.7385 - loss: 0.5358 - val_accuracy: 0.7284 - val_loss: 0.5611
Epoch 59/100
858/858 - 5s - 6ms/step - accuracy: 0.7388 - loss: 0.5352 - val_accuracy: 0.7271 - val_loss: 0.5598
Epoch 60/100
858/858 - 3s - 3ms/step - accuracy: 0.7395 - loss: 0.5355 - val_accuracy: 0.7265 - val_loss: 0.5585
Epoch 61/100
858/858 - 5s - 6ms/step - accuracy: 0.7393 - loss: 0.5351 - val_accuracy: 0.7296 - val_loss: 0.5600
Epoch 62/100
858/858 - 2s - 3ms/step - accuracy: 0.7391 - loss: 0.5349 - val_accuracy: 0.7264 - val_loss: 0.5628
Epoch 63/100
858/858 - 3s - 3ms/step - accuracy: 0.7390 - loss: 0.5356 - val_accuracy: 0.7302 - val_loss: 0.5590
Epoch 64/100
858/858 - 3s - 4ms/step - accuracy: 0.7391 - loss: 0.5346 - val_accuracy: 0.7294 - val_loss: 0.5586
Epoch 65/100
858/858 - 5s - 5ms/step - accuracy: 0.7385 - loss: 0.5350 - val_accuracy: 0.7264 - val_loss: 0.5614
Epoch 66/100
858/858 - 3s - 3ms/step - accuracy: 0.7397 - loss: 0.5346 - val_accuracy: 0.7241 - val_loss: 0.5600
Epoch 67/100
858/858 - 2s - 3ms/step - accuracy: 0.7388 - loss: 0.5347 - val_accuracy: 0.7278 - val_loss: 0.5616
Epoch 68/100
858/858 - 3s - 4ms/step - accuracy: 0.7395 - loss: 0.5349 - val_accuracy: 0.7284 - val_loss: 0.5609
Epoch 69/100
858/858 - 2s - 3ms/step - accuracy: 0.7392 - loss: 0.5348 - val_accuracy: 0.7283 - val_loss: 0.5605
Epoch 70/100
858/858 - 2s - 3ms/step - accuracy: 0.7395 - loss: 0.5342 - val_accuracy: 0.7293 - val_loss: 0.5600
Epoch 71/100
858/858 - 3s - 3ms/step - accuracy: 0.7395 - loss: 0.5343 - val_accuracy: 0.7286 - val_loss: 0.5628
Epoch 72/100
858/858 - 3s - 3ms/step - accuracy: 0.7392 - loss: 0.5341 - val_accuracy: 0.7278 - val_loss: 0.5613
Epoch 73/100
858/858 - 3s - 4ms/step - accuracy: 0.7396 - loss: 0.5343 - val_accuracy: 0.7281 - val_loss: 0.5617
Epoch 74/100
858/858 - 4s - 5ms/step - accuracy: 0.7394 - loss: 0.5342 - val_accuracy: 0.7277 - val_loss: 0.5641
Epoch 75/100
858/858 - 2s - 3ms/step - accuracy: 0.7386 - loss: 0.5341 - val_accuracy: 0.7305 - val_loss: 0.5606
Epoch 76/100
858/858 - 3s - 4ms/step - accuracy: 0.7397 - loss: 0.5337 - val_accuracy: 0.7293 - val_loss: 0.5616
Epoch 77/100
858/858 - 5s - 6ms/step - accuracy: 0.7396 - loss: 0.5338 - val_accuracy: 0.7287 - val_loss: 0.5637
Epoch 78/100
858/858 - 3s - 3ms/step - accuracy: 0.7397 - loss: 0.5341 - val_accuracy: 0.7293 - val_loss: 0.5616
Epoch 79/100
858/858 - 3s - 3ms/step - accuracy: 0.7405 - loss: 0.5340 - val_accuracy: 0.7280 - val_loss: 0.5675
Epoch 80/100
858/858 - 3s - 3ms/step - accuracy: 0.7398 - loss: 0.5345 - val_accuracy: 0.7271 - val_loss: 0.5610
Epoch 81/100
858/858 - 3s - 4ms/step - accuracy: 0.7401 - loss: 0.5337 - val_accuracy: 0.7267 - val_loss: 0.5658
Epoch 82/100
858/858 - 4s - 5ms/step - accuracy: 0.7401 - loss: 0.5338 - val_accuracy: 0.7308 - val_loss: 0.5632
Epoch 83/100
858/858 - 2s - 3ms/step - accuracy: 0.7394 - loss: 0.5337 - val_accuracy: 0.7286 - val_loss: 0.5645
Epoch 84/100
858/858 - 3s - 3ms/step - accuracy: 0.7395 - loss: 0.5338 - val_accuracy: 0.7258 - val_loss: 0.5643
Epoch 85/100
858/858 - 3s - 4ms/step - accuracy: 0.7393 - loss: 0.5333 - val_accuracy: 0.7259 - val_loss: 0.5641
Epoch 86/100
858/858 - 2s - 3ms/step - accuracy: 0.7401 - loss: 0.5337 - val_accuracy: 0.7267 - val_loss: 0.5635
Epoch 87/100
858/858 - 3s - 3ms/step - accuracy: 0.7404 - loss: 0.5334 - val_accuracy: 0.7271 - val_loss: 0.5649
Epoch 88/100
858/858 - 2s - 3ms/step - accuracy: 0.7400 - loss: 0.5331 - val_accuracy: 0.7259 - val_loss: 0.5676
Epoch 89/100
858/858 - 3s - 3ms/step - accuracy: 0.7397 - loss: 0.5334 - val_accuracy: 0.7276 - val_loss: 0.5669
Epoch 90/100
858/858 - 3s - 3ms/step - accuracy: 0.7397 - loss: 0.5330 - val_accuracy: 0.7278 - val_loss: 0.5660
Epoch 91/100
858/858 - 5s - 5ms/step - accuracy: 0.7397 - loss: 0.5327 - val_accuracy: 0.7277 - val_loss: 0.5647
Epoch 92/100
858/858 - 2s - 3ms/step - accuracy: 0.7408 - loss: 0.5330 - val_accuracy: 0.7270 - val_loss: 0.5652
Epoch 93/100
858/858 - 3s - 4ms/step - accuracy: 0.7401 - loss: 0.5340 - val_accuracy: 0.7287 - val_loss: 0.5643
Epoch 94/100
858/858 - 3s - 3ms/step - accuracy: 0.7396 - loss: 0.5324 - val_accuracy: 0.7264 - val_loss: 0.5680
Epoch 95/100
858/858 - 5s - 5ms/step - accuracy: 0.7400 - loss: 0.5330 - val_accuracy: 0.7264 - val_loss: 0.5662
Epoch 96/100
858/858 - 3s - 3ms/step - accuracy: 0.7405 - loss: 0.5324 - val_accuracy: 0.7297 - val_loss: 0.5645
Epoch 97/100
858/858 - 3s - 4ms/step - accuracy: 0.7402 - loss: 0.5334 - val_accuracy: 0.7284 - val_loss: 0.5651
Epoch 98/100
858/858 - 5s - 5ms/step - accuracy: 0.7395 - loss: 0.5331 - val_accuracy: 0.7273 - val_loss: 0.5667
Epoch 99/100
858/858 - 2s - 3ms/step - accuracy: 0.7395 - loss: 0.5330 - val_accuracy: 0.7274 - val_loss: 0.5688
Epoch 100/100
858/858 - 3s - 3ms/step - accuracy: 0.7399 - loss: 0.5332 - val_accuracy: 0.7268 - val_loss: 0.5661

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 1s - 3ms/step - accuracy: 0.7268 - loss: 0.5661
Loss: 0.5660607814788818, Accuracy: 0.7268221378326416

In [17]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.